kind: Deployment
apiVersion: apps/v1
metadata:
  name: facelog-deployment
  labels:
    app: facelog
spec:
  replicas: 3
  selector:
    matchLabels:
      app: facelog
  template:
    metadata:
      name: facelog-container
      labels:
        app: facelog
    spec:
      containers:
      - name: facelog-container
        image: vivekdalsaniya/facelog
        ports:
        - containerPort: 8000
