kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  labels:
    app: nginx-service 
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30001
    targetPort: 80  
