kind: Service
apiVersion: v1
metadata:
  name: facelog-service
  labels:
    app: facelog-service
spec:
  type: NodePort
  selector:
    app: facelog
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30001
    targetPort: 8000
